# Generated by Django 5.1.7 on 2025-07-07 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена услуги')),
                ('duration', models.PositiveIntegerField(default=20, help_text='Время выполнения в минутах', verbose_name='Время выполнения услуги')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная услуга')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/services/', verbose_name='Изображение услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/masters/', verbose_name='Фотография')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('experience', models.PositiveIntegerField(help_text='Опыт работы в годах', verbose_name='Стаж работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('services', models.ManyToManyField(related_name='masters', to='core.service')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Имя клиента')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Плохо'), (2, '2 - Удовлетворительно'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Отлично')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='review_created_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('not_approved', 'Не подтвержден'), ('moderated', 'Прошел модерацию'), ('spam', 'Спам'), ('approved', 'Подтвержден'), ('in_awaiting', 'В ожидании'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='not_approved', max_length=50, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время записи')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.master')),
                ('services', models.ManyToManyField(to='core.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-appointment_date'],
                'indexes': [models.Index(fields=['-appointment_date'], name='appointment_date_desc_idx'), models.Index(fields=['phone', '-appointment_date'], name='phone_-appointment_date_idx')],
            },
        ),
    ]
