# Generated by Django 5.1.7 on 2025-04-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_status_idx_order_created_at_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='core_review_created_713019_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-appointment_date'], name='appointment_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone', '-appointment_date'], name='phone_-appointment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='review_created_at_idx'),
        ),
    ]
